# ---------------------
# DEVELOPMENT STAGE
# ---------------------
FROM node:20-alpine

ARG NEXT_PUBLIC_MUI_LICENSE
ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_MUI_LICENSE=${NEXT_PUBLIC_MUI_LICENSE}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# Install dependencies for development
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies including dev dependencies
RUN npm install

# Copy source code
COPY . .

# for healthcheck
RUN apk add --no-cache curl

# Expose port
EXPOSE 3000

# Set environment variables for development
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Enable hot reload
ENV WATCHPACK_POLLING=true

# Start the development server
CMD ["npm", "run", "dev"]
